openapi: 3.0.1
info:
  description: The API of the Item Relationship Service (IRS) for retrieving item
    graphs along the value chain of CATENA-X partners.
  title: IRS API
  version: "2.0"
servers:
  - url: http://localhost:8080
security:
  - oAuth2:
      - profile email
paths:
  /irs/jobs:
    get:
      description: Returns paginated jobs with state and execution times.
      operationId: getJobsByJobStates
      parameters:
        - description: Requested job states.
          explode: false
          in: query
          name: states
          required: false
          schema:
            type: array
            items:
              type: string
              enum:
                - UNSAVED
                - INITIAL
                - RUNNING
                - TRANSFERS_FINISHED
                - COMPLETED
                - CANCELED
                - ERROR
            maxItems: 2147483647
        - description: Zero-based page index (0..N)
          in: query
          name: page
          required: false
          schema:
            type: integer
            default: 0
            minimum: 0
        - description: The size of the page to be returned
          in: query
          name: size
          required: false
          schema:
            type: integer
            default: 20
            minimum: 1
        - description: "Sorting criteria in the format: property,(asc|desc). Default\
          \ sort order is ascending. Multiple sort criteria are supported."
          in: query
          name: sort
          required: false
          schema:
            type: array
            items:
              type: string
      responses:
        "200":
          content:
            application/json:
              examples:
                complete:
                  $ref: '#/components/examples/complete-job-list-processing-state'
              schema:
                $ref: '#/components/schemas/PageResult'
          description: Paginated list of jobs with state and execution times for requested
            job states.
        "400":
          content:
            application/json:
              examples:
                error:
                  $ref: '#/components/examples/error-response-400'
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Return jobs for requested job states failed.
        "401":
          content:
            application/json:
              examples:
                error:
                  $ref: '#/components/examples/error-response-401'
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Authorized failed.
        "403":
          content:
            application/json:
              examples:
                error:
                  $ref: '#/components/examples/error-response-403'
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Authorized failed.
      security:
        - oAuth2:
            - profile email
      summary: Returns paginated jobs with state and execution times.
      tags:
        - Item Relationship Service
    post:
      description: "Register an IRS job to retrieve an item graph for given {globalAssetId}."
      operationId: registerJobForGlobalAssetId
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterJob'
        required: true
      responses:
        "201":
          content:
            application/json:
              examples:
                complete:
                  $ref: '#/components/examples/job-handle'
              schema:
                $ref: '#/components/schemas/JobHandle'
          description: Returns id of registered job.
        "400":
          content:
            application/json:
              examples:
                error:
                  $ref: '#/components/examples/error-response-400'
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Job registration failed.
        "401":
          content:
            application/json:
              examples:
                error:
                  $ref: '#/components/examples/error-response-401'
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Authorized failed.
        "403":
          content:
            application/json:
              examples:
                error:
                  $ref: '#/components/examples/error-response-403'
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Authorized failed.
      security:
        - oAuth2:
            - profile email
      summary: "Register an IRS job to retrieve an item graph for given {globalAssetId}."
      tags:
        - Item Relationship Service
  /irs/jobs/{id}:
    get:
      description: Return job with optional item graph result for requested id.
      operationId: getJobForJobId
      parameters:
        - description: Id of the job.
          example: 6c311d29-5753-46d4-b32c-19b918ea93b0
          in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
            maxLength: 36
            minLength: 36
        - description: "<true> Return job with current processed item graph. <false>\
          \ Return job with item graph if job is in state <COMPLETED>, otherwise job."
          in: query
          name: returnUncompletedJob
          required: false
          schema:
            type: boolean
            default: true
      responses:
        "200":
          content:
            application/json:
              examples:
                complete:
                  $ref: '#/components/examples/complete-job-result'
              schema:
                $ref: '#/components/schemas/Jobs'
          description: Return job with item graph for the requested id.
        "206":
          content:
            application/json:
              examples:
                complete:
                  $ref: '#/components/examples/partial-job-result'
              schema:
                $ref: '#/components/schemas/Jobs'
          description: Return job with current processed item graph for the requested
            id.
        "400":
          content:
            application/json:
              examples:
                error:
                  $ref: '#/components/examples/error-response-400'
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Return job failed.
        "401":
          content:
            application/json:
              examples:
                error:
                  $ref: '#/components/examples/error-response-401'
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Authorized failed.
        "403":
          content:
            application/json:
              examples:
                error:
                  $ref: '#/components/examples/error-response-403'
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Authorized failed.
        "404":
          content:
            application/json:
              examples:
                error:
                  $ref: '#/components/examples/error-response-404'
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Job with the requested jobId not found.
      security:
        - oAuth2:
            - profile email
      summary: Return job with optional item graph result for requested id.
      tags:
        - Item Relationship Service
    put:
      description: Cancel job for requested jobId.
      operationId: cancelJobByJobId
      parameters:
        - description: Id of the job.
          example: 6c311d29-5753-46d4-b32c-19b918ea93b0
          in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
            maxLength: 36
            minLength: 36
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Job'
          description: Job with requested jobId canceled.
        "400":
          content:
            application/json:
              examples:
                error:
                  $ref: '#/components/examples/error-response-400'
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Cancel job failed.
        "401":
          content:
            application/json:
              examples:
                error:
                  $ref: '#/components/examples/error-response-401'
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Authorized failed.
        "403":
          content:
            application/json:
              examples:
                error:
                  $ref: '#/components/examples/error-response-403'
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Authorized failed.
        "404":
          content:
            application/json:
              examples:
                error:
                  $ref: '#/components/examples/error-response-404'
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Job for requested jobId not found.
      security:
        - oAuth2:
            - profile email
      summary: Cancel job for requested jobId.
      tags:
        - Item Relationship Service
components:
  examples:
    canceled-job-result:
      value:
        bpns: [ ]
        job:
          completedOn: 2022-02-03T14:48:54.709Z
          createdOn: 2022-02-03T14:48:54.709Z
          exception:
            errorDetail: Timeout while requesting Digital Registry
            exception: IrsTimeoutException
            exceptionDate: 2022-02-03T14:48:54.709Z
          globalAssetId: urn:uuid:6c311d29-5753-46d4-b32c-19b918ea93b0
          id: e5347c88-a921-11ec-b909-0242ac120002
          lastModifiedOn: 2022-02-03T14:48:54.709Z
          owner: ""
          parameter:
            aspects:
              - SerialPartTypization
              - AddressAspect
            bomLifecycle: asBuilt
            collectAspects: false
            depth: 4
            direction: downward
            lookupBPNs: false
          startedOn: 2022-02-03T14:48:54.709Z
          state: CANCELED
          summary:
            asyncFetchedItems:
              completed: 0
              failed: 0
              running: 0
        relationships: [ ]
        submodels: [ ]
        tombstones: [ ]
    complete-job-list-processing-state:
      value:
        content:
          - completedOn: 2022-02-03T14:48:54.709Z
            id: 6c311d29-5753-46d4-b32c-19b918ea93b0
            startedOn: 2022-02-03T14:48:54.709Z
            state: COMPLETED
        pageCount: 1
        pageNumber: 0
        pageSize: 10
        totalElements: 1
    complete-job-result:
      value:
        bpns:
          - manufacturerId: BPNL00000003AYRE
            manufacturerName: OEM A
        job:
          completedOn: 2022-02-03T14:48:54.709Z
          createdOn: 2022-02-03T14:48:54.709Z
          exception:
            errorDetail: Timeout while requesting Digital Registry
            exception: IrsTimeoutException
            exceptionDate: 2022-02-03T14:48:54.709Z
          globalAssetId: urn:uuid:6c311d29-5753-46d4-b32c-19b918ea93b0
          id: e5347c88-a921-11ec-b909-0242ac120002
          lastModifiedOn: 2022-02-03T14:48:54.709Z
          owner: ""
          parameter:
            aspects:
              - SerialPartTypization
              - AddressAspect
            bomLifecycle: asBuilt
            collectAspects: false
            depth: 4
            direction: downward
            lookupBPNs: false
          startedOn: 2022-02-03T14:48:54.709Z
          state: COMPLETED
          summary:
            asyncFetchedItems:
              completed: 0
              failed: 0
              running: 0
        relationships:
          - catenaXId: urn:uuid:d9bec1c6-e47c-4d18-ba41-0a5fe8b7f447
            linkedItem:
              assembledOn: 2022-02-03T14:48:54.709Z
              childCatenaXId: urn:uuid:a45a2246-f6e1-42da-b47d-5c3b58ed62e9
              lastModifiedOn: 2022-02-03T14:48:54.709Z
              lifecycleContext: asBuilt
              quantity:
                measurementUnit:
                  datatypeURI: urn:bamm:io.openmanufacturing:meta-model:1.0.0#piece
                  lexicalValue: piece
                quantityNumber: 1.0
        shells:
          - description:
              - language: en
                text: The shell for a vehicle
            globalAssetId:
              value:
                - urn:uuid:a45a2246-f6e1-42da-b47d-5c3b58ed62e9
            idShort: future concept x
            identification: 882fc530-b69b-4707-95f6-5dbc5e9baaa8
            specificAssetIds:
              - key: engineserialid
                value: "12309481209312"
            submodelDescriptors:
              - description:
                  - language: en
                    text: Provides base vehicle information
                endpoints:
                  - interface: HTTP
                    protocolInformation:
                      endpointAddress: https://catena-x.net/vehicle/basedetails/
                      endpointProtocol: HTTPS
                      endpointProtocolVersion: "1.0"
                idShort: vehicle base details
                identification: 4a738a24-b7d8-4989-9cd6-387772f40565
                semanticId:
                  value:
                    - urn:bamm:com.catenax.vehicle:0.1.1
              - description:
                  - language: en
                    text: Provides base vehicle information
                endpoints:
                  - interface: HTTP
                    protocolInformation:
                      endpointAddress: https://catena-x.net/vehicle/partdetails/
                      endpointProtocol: HTTPS
                      endpointProtocolVersion: "1.0"
                idShort: vehicle part details
                identification: dae4d249-6d66-4818-b576-bf52f3b9ae90
                semanticId:
                  value:
                    - urn:bamm:com.catenax.vehicle:0.1.1#PartDetails
        submodels:
          - aspectType: urn:bamm:io.catenax.assembly_part_relationship:1.0.0
            identification: urn:uuid:fc784d2a-5506-4e61-8e34-21600f8cdeff
            payload:
              catenaXId: urn:uuid:d9bec1c6-e47c-4d18-ba41-0a5fe8b7f447
              childParts:
                - assembledOn: 2022-02-03T14:48:54.709Z
                  childCatenaXId: urn:uuid:d9bec1c6-e47c-4d18-ba41-0a5fe8b7f447
                  lastModifiedOn: 2022-02-03T14:48:54.709Z
                  lifecycleContext: AsBuilt
                  quantity:
                    measurementUnit:
                      datatypeURI: urn:bamm:io.openmanufacturing:meta-model:1.0.0#piece
                      lexicalValue: piece
                    quantityNumber: 1
        tombstones:
          - catenaXId: urn:uuid:6c311d29-5753-46d4-b32c-19b918ea93b0
            endpointURL: https://catena-x.net/vehicle/partdetails/
            processingError:
              errorDetail: Details to reason of Failure
              lastAttempt: 2022-02-03T14:48:54.709Z
              retryCounter: 0
    error-response-400:
      value:
        error: Bad request
        messages:
          - BadRequestException
        statusCode: 400 BAD_REQUEST
    error-response-401:
      value:
        error: Unauthorized
        messages:
          - UnauthorizedException
        statusCode: 401 UNAUTHORIZED
    error-response-403:
      value:
        error: Forbidden
        messages:
          - ForbiddenException
        statusCode: 403 FORBIDDEN
    error-response-404:
      value:
        error: Not found
        messages:
          - NotFoundException
        statusCode: 404 NOT_FOUND
    failed-job-result:
      value:
        bpns: [ ]
        job:
          createdOn: 2022-02-03T14:48:54.709Z
          exception:
            errorDetail: Timeout while requesting Digital Registry
            exception: IrsTimeoutException
            exceptionDate: 2022-02-03T14:48:54.709Z
          globalAssetId: urn:uuid:6c311d29-5753-46d4-b32c-19b918ea93b0
          id: e5347c88-a921-11ec-b909-0242ac120002
          lastModifiedOn: 2022-02-03T14:48:54.709Z
          owner: ""
          parameter:
            aspects:
              - SerialPartTypization
              - AddressAspect
            bomLifecycle: asBuilt
            collectAspects: false
            depth: 4
            direction: downward
            lookupBPNs: false
          startedOn: 2022-02-03T14:48:54.709Z
          state: ERROR
          summary:
            asyncFetchedItems:
              completed: 0
              failed: 0
              running: 0
        relationships: [ ]
        submodels: [ ]
        tombstones: [ ]
    job-handle:
      value:
        id: 6c311d29-5753-46d4-b32c-19b918ea93b0
    job-result-without-uncompleted-result-tree:
      value:
        bpns:
          - manufacturerId: BPNL00000003AYRE
            manufacturerName: OEM A
        job:
          completedOn: 2022-02-03T14:48:54.709Z
          createdOn: 2022-02-03T14:48:54.709Z
          exception:
            errorDetail: Timeout while requesting Digital Registry
            exception: IrsTimeoutException
            exceptionDate: 2022-02-03T14:48:54.709Z
          globalAssetId: urn:uuid:6c311d29-5753-46d4-b32c-19b918ea93b0
          id: e5347c88-a921-11ec-b909-0242ac120002
          lastModifiedOn: 2022-02-03T14:48:54.709Z
          owner: ""
          parameter:
            aspects:
              - SerialPartTypization
              - AddressAspect
            bomLifecycle: asBuilt
            collectAspects: false
            depth: 4
            direction: downward
            lookupBPNs: false
          startedOn: 2022-02-03T14:48:54.709Z
          state: COMPLETED
          summary:
            asyncFetchedItems:
              completed: 0
              failed: 0
              running: 0
        relationships:
          - catenaXId: urn:uuid:d9bec1c6-e47c-4d18-ba41-0a5fe8b7f447
            linkedItem:
              assembledOn: 2022-02-03T14:48:54.709Z
              childCatenaXId: urn:uuid:a45a2246-f6e1-42da-b47d-5c3b58ed62e9
              lastModifiedOn: 2022-02-03T14:48:54.709Z
              lifecycleContext: asBuilt
              quantity:
                measurementUnit:
                  datatypeURI: urn:bamm:io.openmanufacturing:meta-model:1.0.0#piece
                  lexicalValue: piece
                quantityNumber: 1.0
        shells:
          - description:
              - language: en
                text: The shell for a vehicle
            globalAssetId:
              value:
                - urn:uuid:a45a2246-f6e1-42da-b47d-5c3b58ed62e9
            idShort: future concept x
            identification: 882fc530-b69b-4707-95f6-5dbc5e9baaa8
            specificAssetIds:
              - key: engineserialid
                value: "12309481209312"
            submodelDescriptors:
              - description:
                  - language: en
                    text: Provides base vehicle information
                endpoints:
                  - interface: HTTP
                    protocolInformation:
                      endpointAddress: https://catena-x.net/vehicle/basedetails/
                      endpointProtocol: HTTPS
                      endpointProtocolVersion: "1.0"
                idShort: vehicle base details
                identification: 4a738a24-b7d8-4989-9cd6-387772f40565
                semanticId:
                  value:
                    - urn:bamm:com.catenax.vehicle:0.1.1
              - description:
                  - language: en
                    text: Provides base vehicle information
                endpoints:
                  - interface: HTTP
                    protocolInformation:
                      endpointAddress: https://catena-x.net/vehicle/partdetails/
                      endpointProtocol: HTTPS
                      endpointProtocolVersion: "1.0"
                idShort: vehicle part details
                identification: dae4d249-6d66-4818-b576-bf52f3b9ae90
                semanticId:
                  value:
                    - urn:bamm:com.catenax.vehicle:0.1.1#PartDetails
        submodels:
          - aspectType: urn:bamm:io.catenax.assembly_part_relationship:1.0.0
            identification: urn:uuid:fc784d2a-5506-4e61-8e34-21600f8cdeff
            payload:
              catenaXId: urn:uuid:d9bec1c6-e47c-4d18-ba41-0a5fe8b7f447
              childParts:
                - assembledOn: 2022-02-03T14:48:54.709Z
                  childCatenaXId: urn:uuid:d9bec1c6-e47c-4d18-ba41-0a5fe8b7f447
                  lastModifiedOn: 2022-02-03T14:48:54.709Z
                  lifecycleContext: AsBuilt
                  quantity:
                    measurementUnit:
                      datatypeURI: urn:bamm:io.openmanufacturing:meta-model:1.0.0#piece
                      lexicalValue: piece
                    quantityNumber: 1
        tombstones:
          - catenaXId: urn:uuid:6c311d29-5753-46d4-b32c-19b918ea93b0
            endpointURL: https://catena-x.net/vehicle/partdetails/
            processingError:
              errorDetail: Details to reason of Failure
              lastAttempt: 2022-02-03T14:48:54.709Z
              retryCounter: 0
    partial-job-result:
      value:
        bpns: [ ]
        job:
          completedOn: 2022-02-03T14:48:54.709Z
          createdOn: 2022-02-03T14:48:54.709Z
          exception:
            errorDetail: Timeout while requesting Digital Registry
            exception: IrsTimeoutException
            exceptionDate: 2022-02-03T14:48:54.709Z
          globalAssetId: urn:uuid:6c311d29-5753-46d4-b32c-19b918ea93b0
          id: e5347c88-a921-11ec-b909-0242ac120002
          lastModifiedOn: 2022-02-03T14:48:54.709Z
          owner: ""
          parameter:
            aspects:
              - SerialPartTypization
              - AddressAspect
            bomLifecycle: asBuilt
            collectAspects: false
            depth: 4
            direction: downward
            lookupBPNs: false
          startedOn: 2022-02-03T14:48:54.709Z
          state: RUNNING
          summary:
            asyncFetchedItems:
              completed: 0
              failed: 0
              running: 0
        relationships: [ ]
        submodels: [ ]
        tombstones: [ ]
  schemas:
    AdministrativeInformation:
      type: object
      additionalProperties: false
      properties:
        revision:
          type: string
        version:
          type: string
    AssetAdministrationShellDescriptor:
      type: object
      additionalProperties: false
      description: AAS shells.
      properties:
        administration:
          $ref: '#/components/schemas/AdministrativeInformation'
        description:
          type: array
          items:
            $ref: '#/components/schemas/LangString'
          maxItems: 2147483647
        globalAssetId:
          $ref: '#/components/schemas/Reference'
        idShort:
          type: string
        identification:
          type: string
        specificAssetIds:
          type: array
          items:
            $ref: '#/components/schemas/IdentifierKeyValuePair'
          maxItems: 2147483647
        submodelDescriptors:
          type: array
          items:
            $ref: '#/components/schemas/SubmodelDescriptor'
          maxItems: 2147483647
    AsyncFetchedItems:
      type: object
      additionalProperties: false
      description: Statistics of job execution.
      properties:
        completed:
          type: integer
          format: int32
          description: Number of completed item transfers.
          maximum: 2147483647
          minimum: 0
        failed:
          type: integer
          format: int32
          description: Number of failed item transfers.
          maximum: 2147483647
          minimum: 0
        running:
          type: integer
          format: int32
          description: Number of running item transfers.
          maximum: 2147483647
          minimum: 0
    Bpn:
      type: object
      additionalProperties: false
      description: Business partner id with name
      properties:
        manufacturerId:
          type: string
        manufacturerName:
          type: string
    Endpoint:
      type: object
      additionalProperties: false
      properties:
        interface:
          type: string
        protocolInformation:
          $ref: '#/components/schemas/ProtocolInformation'
    ErrorResponse:
      type: object
      additionalProperties: false
      description: Error response.
      properties:
        error:
          type: string
          description: Error.
        messages:
          type: array
          description: List of error messages.
          items:
            type: string
          maxItems: 2147483647
        statusCode:
          type: string
          description: Error code.
          enum:
            - 100 CONTINUE
            - 101 SWITCHING_PROTOCOLS
            - 102 PROCESSING
            - 103 CHECKPOINT
            - 200 OK
            - 201 CREATED
            - 202 ACCEPTED
            - 203 NON_AUTHORITATIVE_INFORMATION
            - 204 NO_CONTENT
            - 205 RESET_CONTENT
            - 206 PARTIAL_CONTENT
            - 207 MULTI_STATUS
            - 208 ALREADY_REPORTED
            - 226 IM_USED
            - 300 MULTIPLE_CHOICES
            - 301 MOVED_PERMANENTLY
            - 302 FOUND
            - 302 MOVED_TEMPORARILY
            - 303 SEE_OTHER
            - 304 NOT_MODIFIED
            - 305 USE_PROXY
            - 307 TEMPORARY_REDIRECT
            - 308 PERMANENT_REDIRECT
            - 400 BAD_REQUEST
            - 401 UNAUTHORIZED
            - 402 PAYMENT_REQUIRED
            - 403 FORBIDDEN
            - 404 NOT_FOUND
            - 405 METHOD_NOT_ALLOWED
            - 406 NOT_ACCEPTABLE
            - 407 PROXY_AUTHENTICATION_REQUIRED
            - 408 REQUEST_TIMEOUT
            - 409 CONFLICT
            - 410 GONE
            - 411 LENGTH_REQUIRED
            - 412 PRECONDITION_FAILED
            - 413 PAYLOAD_TOO_LARGE
            - 413 REQUEST_ENTITY_TOO_LARGE
            - 414 URI_TOO_LONG
            - 414 REQUEST_URI_TOO_LONG
            - 415 UNSUPPORTED_MEDIA_TYPE
            - 416 REQUESTED_RANGE_NOT_SATISFIABLE
            - 417 EXPECTATION_FAILED
            - 418 I_AM_A_TEAPOT
            - 419 INSUFFICIENT_SPACE_ON_RESOURCE
            - 420 METHOD_FAILURE
            - 421 DESTINATION_LOCKED
            - 422 UNPROCESSABLE_ENTITY
            - 423 LOCKED
            - 424 FAILED_DEPENDENCY
            - 425 TOO_EARLY
            - 426 UPGRADE_REQUIRED
            - 428 PRECONDITION_REQUIRED
            - 429 TOO_MANY_REQUESTS
            - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
            - 451 UNAVAILABLE_FOR_LEGAL_REASONS
            - 500 INTERNAL_SERVER_ERROR
            - 501 NOT_IMPLEMENTED
            - 502 BAD_GATEWAY
            - 503 SERVICE_UNAVAILABLE
            - 504 GATEWAY_TIMEOUT
            - 505 HTTP_VERSION_NOT_SUPPORTED
            - 506 VARIANT_ALSO_NEGOTIATES
            - 507 INSUFFICIENT_STORAGE
            - 508 LOOP_DETECTED
            - 509 BANDWIDTH_LIMIT_EXCEEDED
            - 510 NOT_EXTENDED
            - 511 NETWORK_AUTHENTICATION_REQUIRED
    GlobalAssetIdentification:
      type: object
      additionalProperties: false
      description: CATENA-X global asset id in the format urn:uuid:uuid4.
      properties:
        globalAssetId:
          type: string
          description: CATENA-X global asset id in the format urn:uuid:uuid4.
          example: urn:uuid:6c311d29-5753-46d4-b32c-19b918ea93b0
          maxLength: 45
          minLength: 45
          pattern: "^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
    IdentifierKeyValuePair:
      type: object
      additionalProperties: false
      properties:
        key:
          type: string
        semanticId:
          $ref: '#/components/schemas/Reference'
        subjectId:
          $ref: '#/components/schemas/Reference'
        value:
          type: string
    Job:
      type: object
      additionalProperties: false
      description: Executable unit with meta information and item graph result.
      properties:
        completedOn:
          type: string
          format: date-time
        createdOn:
          type: string
          format: date-time
        exception:
          $ref: '#/components/schemas/JobErrorDetails'
        globalAssetId:
          $ref: '#/components/schemas/GlobalAssetIdentification'
        id:
          type: string
          format: uuid
          description: Id of the job.
          maxLength: 36
          minLength: 36
          pattern: "/^[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12}$/i"
        lastModifiedOn:
          type: string
          format: date-time
        owner:
          type: string
          description: The IRS api consumer.
        parameter:
          $ref: '#/components/schemas/JobParameter'
        startedOn:
          type: string
          format: date-time
        state:
          type: string
          enum:
            - UNSAVED
            - INITIAL
            - RUNNING
            - TRANSFERS_FINISHED
            - COMPLETED
            - CANCELED
            - ERROR
        summary:
          $ref: '#/components/schemas/Summary'
      required:
        - globalAssetId
        - id
        - state
    JobErrorDetails:
      type: object
      additionalProperties: false
      description: Job error details.
      properties:
        errorDetail:
          type: string
          description: Detailed exception information.
          maxLength: 4000
        exception:
          type: string
          description: Exception name.
          maxLength: 100
        exceptionDate:
          type: string
          format: date-time
          description: Datetime error occurs.
    JobHandle:
      type: object
      additionalProperties: false
      properties:
        id:
          type: string
          format: uuid
          description: Id of the job.
          maxLength: 36
          minLength: 36
          pattern: "/^[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12}$/i"
    JobParameter:
      type: object
      additionalProperties: false
      description: Job parameter of job processing.
      properties:
        aspects:
          type: string
          enum:
            - AddressAspect
            - AssemblyPartRelationship
            - Batch
            - BatteryPass
            - CertificateOfDestruction
            - CertificateOfDismantler
            - ChargingProcess
            - ClaimData
            - DiagnosticData
            - EndOfLife
            - EsrCertificate
            - EsrCertificateStateStatistic
            - IdConversion
            - MarketplaceOffer
            - MaterialForHomologation
            - MaterialForRecycling
            - PartAsPlanned
            - PhysicalDimension
            - ProductDescription
            - ReturnRequest
            - SerialPartTypization
            - SingleLevelBomAsPlanned
            - SingleLevelUsageAsBuilt
        bomLifecycle:
          type: string
          description: The lifecycle context in which the child part was assembled
            into the parent part.
          enum:
            - asBuilt
            - asPlanned
        callbackUrl:
          type: string
        collectAspects:
          type: boolean
        depth:
          type: integer
          format: int32
          maximum: 2147483647
          minimum: 0
        direction:
          type: string
          description: Item graph traversal direction.
          enum:
            - upward
            - downward
        lookupBPNs:
          type: boolean
    JobStatusResult:
      type: object
      additionalProperties: false
      properties:
        completedOn:
          type: string
          format: date-time
        id:
          type: string
          format: uuid
        startedOn:
          type: string
          format: date-time
        state:
          type: string
          enum:
            - UNSAVED
            - INITIAL
            - RUNNING
            - TRANSFERS_FINISHED
            - COMPLETED
            - CANCELED
            - ERROR
    Jobs:
      type: object
      additionalProperties: false
      description: Container for a job with item graph.
      properties:
        bpns:
          type: array
          description: Collection of bpn mappings
          items:
            $ref: '#/components/schemas/Bpn'
          maxItems: 2147483647
          uniqueItems: true
        job:
          $ref: '#/components/schemas/Job'
        relationships:
          type: array
          description: Relationships between parent and child items.
          items:
            $ref: '#/components/schemas/Relationship'
          maxItems: 2147483647
        shells:
          type: array
          description: AAS shells.
          items:
            $ref: '#/components/schemas/AssetAdministrationShellDescriptor'
          maxItems: 2147483647
        submodels:
          type: array
          description: Collection of requested Submodels
          items:
            $ref: '#/components/schemas/Submodel'
          maxItems: 2147483647
        tombstones:
          type: array
          description: Collection of not resolvable endpoints as tombstones. Including
            cause of error and endpoint URL.
          items:
            $ref: '#/components/schemas/Tombstone'
          maxItems: 2147483647
    LangString:
      type: object
      additionalProperties: false
      properties:
        language:
          type: string
        text:
          type: string
    LinkedItem:
      type: object
      additionalProperties: false
      description: Set of child parts the parent object is assembled by (one structural
        level down).
      properties:
        assembledOn:
          type: string
          format: date-time
          description: Datetime of assembly.
        childCatenaXId:
          $ref: '#/components/schemas/GlobalAssetIdentification'
        lastModifiedOn:
          type: string
          format: date-time
          description: Last datetime item was modified.
        lifecycleContext:
          type: string
          description: The lifecycle context in which the child part was assembled
            into the parent part.
          enum:
            - asBuilt
            - asPlanned
        quantity:
          $ref: '#/components/schemas/Quantity'
    MeasurementUnit:
      type: object
      additionalProperties: false
      properties:
        datatypeURI:
          type: string
        lexicalValue:
          type: string
    PageResult:
      type: object
      additionalProperties: false
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/JobStatusResult'
        pageCount:
          type: integer
          format: int32
        pageNumber:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        totalElements:
          type: integer
          format: int32
    ProcessingError:
      type: object
      additionalProperties: false
      properties:
        errorDetail:
          type: string
        lastAttempt:
          type: string
          format: date-time
        processStep:
          type: string
          enum:
            - SUBMODEL_REQUEST
            - DIGITAL_TWIN_REQUEST
            - SCHEMA_VALIDATION
            - SCHEMA_REQUEST
            - BPDM_REQUEST
            - BPDM_VALIDATION
        retryCounter:
          type: integer
          format: int32
          maximum: 2147483647
          minimum: 0
    ProtocolInformation:
      type: object
      additionalProperties: false
      properties:
        endpointAddress:
          type: string
        endpointProtocol:
          type: string
        endpointProtocolVersion:
          type: string
        subprotocol:
          type: string
        subprotocolBody:
          type: string
        subprotocolBodyEncoding:
          type: string
    Quantity:
      type: object
      additionalProperties: false
      description: Quantity component.
      properties:
        measurementUnit:
          $ref: '#/components/schemas/MeasurementUnit'
        quantityNumber:
          type: number
          format: double
          maximum: 2147483647
          minimum: 0
    Reference:
      type: object
      additionalProperties: false
      properties:
        value:
          type: array
          items:
            type: string
          maxItems: 2147483647
    RegisterJob:
      type: object
      additionalProperties: false
      description: The requested job definition.
      properties:
        aspects:
          type: array
          items:
            type: string
            enum:
              - AddressAspect
              - AssemblyPartRelationship
              - Batch
              - BatteryPass
              - CertificateOfDestruction
              - CertificateOfDismantler
              - ChargingProcess
              - ClaimData
              - DiagnosticData
              - EndOfLife
              - EsrCertificate
              - EsrCertificateStateStatistic
              - IdConversion
              - MarketplaceOffer
              - MaterialForHomologation
              - MaterialForRecycling
              - PartAsPlanned
              - PhysicalDimension
              - ProductDescription
              - ReturnRequest
              - SerialPartTypization
              - SingleLevelBomAsPlanned
              - SingleLevelUsageAsBuilt
          maxItems: 2147483647
        bomLifecycle:
          type: string
          description: The lifecycle context in which the child part was assembled
            into the parent part.
          enum:
            - asBuilt
            - asPlanned
        callbackUrl:
          type: string
          description: "Callback url to notify requestor when job processing is finished.\
            \ There are two uri variable placeholders that can be used: jobId and\
            \ jobState."
          example: "https://hostname.com/callback?jobId={jobId}&jobState={jobState}"
        collectAspects:
          type: boolean
          description: Flag to specify whether aspects should be requested and collected.
            Default is false.
        depth:
          type: integer
          format: int32
          description: Max depth of the item graph returned. If no depth is set item
            graph with max depth is returned.
          maximum: 100
          minimum: 1
        direction:
          type: string
          default: downward
          description: Item graph traversal direction.
          enum:
            - upward
            - downward
        globalAssetId:
          type: string
          description: Id of global asset.
          example: urn:uuid:6c311d29-5753-46d4-b32c-19b918ea93b0
          maxLength: 45
          minLength: 45
          pattern: "^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
        lookupBPNs:
          type: boolean
          description: Flag to specify whether BPNs should be collected and resolved
            via the configured BPDM URL. Default is false.
      required:
        - globalAssetId
    Relationship:
      type: object
      additionalProperties: false
      description: Relationships between parent and child items.
      properties:
        aspectType:
          type: string
        catenaXId:
          $ref: '#/components/schemas/GlobalAssetIdentification'
        linkedItem:
          $ref: '#/components/schemas/LinkedItem'
    Submodel:
      type: object
      additionalProperties: false
      description: "Submodel with identification of SubmodelDescriptor, aspect type\
        \ and payload as String"
      properties:
        aspectType:
          type: string
        identification:
          type: string
        payload:
          type: object
          additionalProperties:
            type: object
    SubmodelDescriptor:
      type: object
      additionalProperties: false
      properties:
        administration:
          $ref: '#/components/schemas/AdministrativeInformation'
        description:
          type: array
          items:
            $ref: '#/components/schemas/LangString'
          maxItems: 2147483647
        endpoints:
          type: array
          items:
            $ref: '#/components/schemas/Endpoint'
          maxItems: 2147483647
        idShort:
          type: string
        identification:
          type: string
        semanticId:
          $ref: '#/components/schemas/Reference'
    Summary:
      type: object
      additionalProperties: false
      description: Summary of the job with statistics of the job processing.
      properties:
        asyncFetchedItems:
          $ref: '#/components/schemas/AsyncFetchedItems'
        bpnLookups:
          $ref: '#/components/schemas/AsyncFetchedItems'
    Tombstone:
      type: object
      additionalProperties: false
      description: Tombstone with information about request failure
      properties:
        catenaXId:
          type: string
          description: CATENA-X global asset id in the format urn:uuid:uuid4.
          example: urn:uuid:6c311d29-5753-46d4-b32c-19b918ea93b0
          maxLength: 45
          minLength: 45
          pattern: "^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
        endpointURL:
          type: string
        processingError:
          $ref: '#/components/schemas/ProcessingError'
  securitySchemes:
    oAuth2:
      flows:
        clientCredentials:
          scopes:
            profile email: ""
          tokenUrl: http://localhost
      type: oauth2
